#!/bin/bash

# Obtiene el volumen actual del dispositivo de entrada predeterminado
current_volume=$(pactl list sources | grep 'Volume:' | head -n 1 | awk -F '/' '{print $2}' | tr -d ' %')

# Define dos niveles de volumen que deseas alternar
volume1=0  # Primer volumen
volume2=100  # Segundo volumen

# Verifica el volumen actual y alterna entre los dos niveles
if [ $current_volume -eq $volume1 ]; then
    # Si el volumen actual es igual al primer volumen, cambia al segundo volumen
    pactl set-source-volume @DEFAULT_SOURCE@ $volume2%
    echo "Volumen cambiado a $volume2%"
else
    # Si el volumen actual es diferente al primer volumen, cambia al primer volumen
    pactl set-source-volume @DEFAULT_SOURCE@ $volume1%
    echo "Volumen cambiado a $volume1%"
fi
