# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  boot.supportedFilesystems = ["btrfs" "apfs" "xfs"];

  #boot.plymouth.enable = true;
  boot.loader.grub = {
    enable = true;
    efiSupport = true;
    efiInstallAsRemovable = true;
    device = "nodev";
    extraEntries = ''
      menuentry "MacOS" {
        search --file --no-floppy --set=root /EFI/OC/OpenCore.efi
        chainloader /EFI/OC/OpenCore.efi
      }
    '';
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5120c1e5-4da4-4a13-8e4f-8e6e4bfebfa8";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/04D3-B94E";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/e3f41777-8a33-4c9f-94b6-62a4fe1d7eec";}
  ];
  
 # fileSystems."/run/media/diegopyl/Disco1".device = "/dev/disk/by-uuid/60d52e98-0213-45cb-a59b-b528a3835ac6";

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
